Repository Flea00012/Group-webDev1, pull requests merged in 2020-11, with the labels that each got.

#5 first commit
  README.md
Labels: enhancement

#17 Created the Post class (for real), and defined association with the U…
  src/main/java/se/kth/sda/skeleton/post/Post.java
  src/main/java/se/kth/sda/skeleton/post/PostController.java
  src/main/java/se/kth/sda/skeleton/post/PostRepository.java
  src/main/java/se/kth/sda/skeleton/post/PostService.java
Labels: enhancement

#19 Eo 6 comment entity
  src/main/java/se/kth/sda/skeleton/comments/Comment.java
  src/main/java/se/kth/sda/skeleton/comments/CommentController.java
  src/main/java/se/kth/sda/skeleton/comments/CommentRepository.java
  src/main/java/se/kth/sda/skeleton/comments/CommentService.java
Labels: enhancement

#20 Added controller methods
  src/main/java/se/kth/sda/skeleton/user/User.java
  src/main/java/se/kth/sda/skeleton/user/UserController.java
Labels: enhancement

#23 Fixed the bugs for comment and post entities.
  src/main/java/se/kth/sda/skeleton/comments/Comment.java
  src/main/java/se/kth/sda/skeleton/comments/CommentService.java
  src/main/java/se/kth/sda/skeleton/post/PostRepository.java
Labels: bug

#18 created CSS folder with proposed responsive design
  frontend/package.json
  frontend/src/CSS/_shared.css
  frontend/src/CSS/_variables.css
  frontend/src/CSS/styles.css
Labels: enhancement

#27 updated the relationships for the user, comments, and posts to specif…
  src/main/java/se/kth/sda/skeleton/SkeletonApplication.java
  src/main/java/se/kth/sda/skeleton/comments/Comment.java
  src/main/java/se/kth/sda/skeleton/post/Post.java
  src/main/java/se/kth/sda/skeleton/user/User.java
  src/main/java/se/kth/sda/skeleton/user/UserController.java
Labels: bug, enhancement

#28 Changed the field names (postBody -> body & poster -> user) to be mor…
  src/main/java/se/kth/sda/skeleton/post/Post.java
Labels: enhancement

#50 TimeStamp Added
  frontend/src/components/posts/Comments/CommentCard.jsx
  frontend/src/components/posts/Comments/CommentCreateForm.jsx
  frontend/src/components/posts/Comments/Comments.jsx
  frontend/src/components/posts/Posts/PostCard.jsx
  frontend/src/components/posts/Posts/PostCreateForm.jsx
  frontend/src/components/posts/Posts/Posts.jsx
  src/main/java/se/kth/sda/skeleton/comments/Comment.java
  src/main/java/se/kth/sda/skeleton/post/Post.java
Labels: enhancement

#52 updated the external APIs and troubleshooting the API response
  frontend/package.json
  frontend/src/components/externalApis/AdBox.jsx
Labels: enhancement
